Added an Avatar for a user
fave77/pbchess pull request #140
Opened 2021-05-18 00:46 UTC by tend2infinity

This will close issue #35 
I have created another model for Avatar properties and linked that with the profile model. While on the frontend side I've used the required states and updated the state as well. 
Reference Video:

https://user-images.githubusercontent.com/61948033/118573443-33677280-b7a0-11eb-8d88-90501f22546e.mp4

2021-05-18 08:54 UTC, fave77 requested changes
@tend2infinity Good job implementing the feature as requested. However, two major changes need to be addressed before merging this PR.

- Make a separate button for `Edit Avatar`
- Don't make a separate model for `Avatar`

Although the functional requirements have been met, the code is too tightly coupled and less cohesive. For example, you are setting the default values of the prefilled avatar schema inside `user-controller.js`. In this case, you could have delegated that task to the client or create a separate service on the server.

The point is that there are multiple scenarios for structuring the code better and I have listed some of those that I could. 

Please make the necessary changes and don't change anything from a functional standpoint as this looks good except for the button.

Looking forward to your updated PR 👍🏻

2021-05-18 08:54 UTC, fave77 commented on client/src/components/profile/profile.js
> +                    src={`https://avataaars.io/?avatarStyle=Circle&topType=${avatar.top}&accessoriesType=${avatar.accessories}&hairColor=${avatar.hairColor}&facialHairType=${avatar.facialColor}&cloth
Use the `avataaars` npm package to render the profile pic, like so:

```bash
<Avatar
  avatarStyle=''
  topType=''
  accessoriesType=''
  facialHairType=''
  clotheType=''
  eyeType=''
  eyebrowType=''
  mouthType=''
  skinColor=''
/>
```

2021-05-18 08:54 UTC, fave77 commented on server/src/models/avatar.model.js
> +const mongoose = require('mongoose')
Do not create a separate model for `Avatar`

2021-05-18 08:54 UTC, fave77 commented on server/src/controllers/user.controller.js
> +  const newAvatar = new Avatar({
Please pass these values from the front-end only, and make the user-controller as loosely coupled as possible.

2021-05-18 08:54 UTC, fave77 commented on client/src/components/profile/editprofile.js
> +          {/* Avatar Properties */}
Create a separate file for edit-avatar inside `profile` folder, and refactor all the avatar-related boilerplate. You can also make the state separate as well, by making a completely different button for the edit avatar `pencil icon` attached to the profile pic.

So, Edit Profile will only edit the full name, country, etc, whereas Pencil Icon (edit avatar button attached next to profile pic) will change only avatar.

Both will hit the same endpoint for now - PUT `/edit-profile`

NOTE: Separating state is optional, whichever works best just proceed with it but you do need to implement the separate button and refactor the boiler plate.

2021-05-18 08:54 UTC, fave77 commented on client/src/components/profile/editprofile.js
> +      top: avatar.top,
Have these states related to avatar completely cohesive into one object called `avatar` or make the state completely isolated.

2021-05-18 08:54 UTC, fave77 commented on client/src/components/profile/editprofile.js
> +
These boilerplate methods should be refactored into a separate `editavatar.js` file.

2021-05-18 08:54 UTC, fave77 commented on client/src/components/profile/editprofile.js
> +      avatar:'',
Have these states related to avatar completely cohesive into one object called avatar or make the state completely isolated.

2021-05-18 12:13 UTC, tend2infinity commented
@fave77 I made a separate model because in that issue it was mentioned that I need to change the avatar type into object Id and use a ref to link another model which will contain the properties. I did that just to reduce the amount of information in the profile model but nevermind now I'll condense that in the profile model itself

2021-05-18 12:37 UTC, apurv-1 commented on client/src/components/profile/editprofile.js
> +    console.log(avatar.top);
Please don't leave these console logs on production!

2021-05-18 12:37 UTC, apurv-1 commented on server/src/controllers/profile.controller.js
> +    console.log(profile)
and just make sure to remove these before the final merge.

2021-05-27 02:44 UTC, tend2infinity commented
Hey, @fave77 I've made the required changes. I resolved almost all of your issues except one in which you told me to initialize the default properties of an avatar from the frontend! For this issue, I would recommend doing it from the backend itself because if we implement that from the frontend then, whenever a new user gets registered **the profile model will not contain the initial properties of the avatar in the avatar field**. That would create a problem because every time when we get to the profile page, all the information of that particular user is fetched from the **"profiles"** model and not from the frontend. We may tackle this issue by initializing an "empty string" at the time of registration of a new user and then making a check in the frontend after getting the information from the '/fetch' route that looks something like

` if (avatar.top===' ' && avatar.accessories === ' ' && avatar.hairColor === ' '&&& .....) 
{
top:"LongHairStraight",
      accessories:"Blank",
      hairColor:"BrownDark",
      facialHair:"Blank",
      clothes:"BlazerShirt",
      eyes:"Default",
      eyebrow:"Default",
      mouth:"Default",
      skin:"Light",
      clothColor: "Black"
}
`
But I feel like this kind of logic isn't the best suited, tell me what you think about it

2021-05-27 07:46 UTC, fave77 approved these changes
@tend2infinity Looks fine to me! However, I can see you have added some additional styling so just provide a demo video for the latest changes. Will merge then 👍🏻 

Great job btw!!

2021-05-27 07:46 UTC, fave77 commented on server/src/controllers/user.controller.js
> +    },
This will do!

2021-05-27 13:46 UTC, tend2infinity commented
Video:

Uploading bandicam 2021-05-27 19-13-03-618.mp4…

2021-05-27 13:47 UTC, tend2infinity commented
Video:

https://user-images.githubusercontent.com/61948033/119837411-2e34c100-bf20-11eb-94de-846f3bfd79e2.mp4

2021-05-27 15:32 UTC, fave77 approved these changes

2021-05-27 15:32 UTC, merged