footer added
fave77/pbchess pull request #19
Opened 2021-02-14 06:48 UTC by pankajkumarbij

Footer added with social media icons.
You can replace dummy data with your original data and social media links.

This footer is completely responsive.

![screencapture-3000-silver-fish-2yydtxe7-ws-us03-gitpod-io-2021-02-14-12_13_34](https://user-images.githubusercontent.com/59636849/107870477-a0781d00-6ebe-11eb-8ad5-75c4979cd2bb.png)

2021-02-14 06:49 UTC, pankajkumarbij commented
> Solved Issue: #5  
Footer added with social media icons.
> You can replace dummy data with your original data and social media links.
> 
> This footer is completely responsive.
> 
> ![screencapture-3000-silver-fish-2yydtxe7-ws-us03-gitpod-io-2021-02-14-12_13_34](https://user-images.githubusercontent.com/59636849/107870477-a0781d00-6ebe-11eb-8ad5-75c4979cd2bb.png)

2021-02-14 08:29 UTC, fave77 requested changes
@pankajkumarbij Please adhere to the basic requirements mentioned in issue #5 
If you want to make some additional inputs, first discuss it on discord.

2021-02-14 08:29 UTC, fave77 commented on server/package-lock.json
> +  "lockfileVersion": 2,
Changes in `server/package-lock.json` aren't required for issue #5

2021-02-14 08:29 UTC, fave77 commented on client/src/App.js
> +        <br/><br/><br/>
Render the footer only in the `Home` component

2021-02-14 08:29 UTC, fave77 commented on client/package.json
> +    "@fortawesome/fontawesome-svg-core": "^1.2.34",
Do not include social media icons

2021-02-15 16:56 UTC, fave77 requested changes
@pankajkumarbij
- This PR shouldn't change `package.json` or `package-lock.json`
- You don't need to use any external library
- Just add the required 3 items since the goal is to keep the design minimal
- Please discuss the design decisions over Discord before making PR

2021-02-16 03:05 UTC, pankajkumarbij commented
I will make a new PR again.

2021-02-16 03:05 UTC, closed without merging