Fixed #7 : Unit testing for NavBar, Login, Lobby and the PrivateRouter components
fave77/pbchess pull request #21
Opened 2021-02-24 14:43 UTC by Subhra264

### Description
Fixed unit testing for NavBar, Login, Lobby and PrivateRouter components.

### Motivation and Context
N.A.

### How Has This Been Tested?
Using Jest and react testing library

### Screenshots (if appropriate):
N.A.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ]  New feature (non-breaking change which adds functionality)
- [ ]  Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [ ]  My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.

2021-02-24 15:44 UTC, fave77 requested changes
@Subhra264 Sorry for the inconvenience :disappointed:

Earlier, I wanted you to pass on the `Profile` component since I was waiting for issue #11 to be resolved first. Now, as it did, it would be great if you can also fix the unit test for rendering the `Profile` component

2021-02-24 16:04 UTC, Subhra264 commented
Ohh, sure I will do...

2021-02-25 15:42 UTC, Subhra264 commented
After the recent merge, the previous error went away somehow😅😅, so just needed to wrap the Profile component with Router.😁😁

2021-02-25 16:28 UTC, fave77 approved these changes

2021-02-25 16:29 UTC, merged