Provide an article on chess - Chess Vocab: Speaking the common tongue ( issue #29 )
fave77/pbchess pull request #44
Opened 2021-03-11 18:07 UTC by Arshanshagarwal

I have added a list of all chess-related words in alphabetical order along with one or two-line descriptions for each. I also made an indexing system to access each Alphabetic group easily.

Screenshots: 

![Learn](https://user-images.githubusercontent.com/50940817/110833576-97fae280-82c2-11eb-8bb5-4ef54d83e5cd.PNG)

![learn 2](https://user-images.githubusercontent.com/50940817/110833583-992c0f80-82c2-11eb-8412-4e29322f1c2f.PNG)

2021-03-11 19:54 UTC, adi-g15 approved these changes
Looks Good to me 👍

@fave77

2021-03-11 19:54 UTC, adi-g15 commented on client/src/components/learn/Terms.json
> +      "meaning": "Overworked, also known as overloaded, is a tactical weakness in chess where a piece is tasked to defend multiple threats at the same time. In many cases, this results in the overwor
Typo: ~preform~ _perform_

2021-03-11 20:01 UTC, adi-g15 approved these changes
![image](https://user-images.githubusercontent.com/37269665/110847082-7d306a00-82d2-11eb-945c-1656b5347088.png)

These aren't errors, but can be fixed @Arshanshagarwal , this is causing the Codacy action to fail>
As for codecov ignore it for now, it's since more code has been added, and existing tests not covering it.

2021-03-11 20:30 UTC, fave77 requested changes
@Arshanshagarwal please make the following changes:
- The styling have unintended effects on home page, like so:
<a href="https://ibb.co/Jx5VVf1"><img src="https://i.ibb.co/k3QjjR7/IMG-20210312-014349.jpg" alt="IMG-20210312-014349" border="0" width="200px"></a>
<a href="https://ibb.co/KGCmjkz"><img src="https://i.ibb.co/JdXCR4F/IMG-20210312-014330.jpg" alt="IMG-20210312-014330" border="0" width="400px"></a>
- Do not modify anything inside `Learn` component, except for maybe alignment (if needed)
- Create a `Vocabs` component along with your json, js, css, and just import that inside `Learn` component, like so:
```bash
...
const Learn = _ => {
  return (
    <Vocabs /> // the component should be here, just before Videos
    <Videos />
  );
};
```
- Choose class-names with extra caution, it might be the reason for homepage's styling issue

2021-03-12 09:49 UTC, fave77 requested changes
@Arshanshagarwal just do the following and your PR will be merged:
- get rid of the `placeholder-img` selector in both `vocab.css` and `learn.css`
- always name the folder of a component in a lower-case format, so `Vocab` to `vocab` (there's no right way, but since the codebase adheres to that, so follow this for the sake of consistency)
- speaking of consistency, export the component at the last line, not while declaring it
- lastly, make the learn component `functional` since it is stateless
```bash
...
const Learn = _ => {
  return (
    <Vocabs />
    <Videos />
  )
};

export default Learn;
```

- (Optional) - provide smooth scrolling when someone clicks an alpahbet

2021-03-12 11:33 UTC, fave77 requested changes
- `learn` shouldn't contain json file
- please squash your commits going forward as that prompts into a frequent PR update (I'm letting it pass this time, so no need to squash now for this PR)
@Arshanshagarwal

2021-03-12 11:33 UTC, fave77 commented on client/src/components/learn/learn.js
> +    <>
Use a wrapper div

2021-03-12 11:33 UTC, fave77 commented on client/src/components/vocab/vocab.js
> +import React, { Component } from "./../../../node_modules/react";
Import libraries the proper way

2021-03-12 16:00 UTC, fave77 approved these changes

2021-03-12 16:01 UTC, merged